#lang racket/base

(require pollen/tag)
(require pollen/decode)

(provide (all-defined-out))
(define chapter (make-tag-function 'h2))
(define list (make-tag-function 'ul))
(define numbered (make-tag-function 'ol))
(define item (make-tag-function 'li 'p))
(define (link url text) `(a [[href ,url]] ,text))
(define q smart-quotes)
(define d smart-dashes)
(define rarr 'rarr)
(define md   'mdash)
(define nd   'ndash)
(define nbsp 'nbsp)
(define etc  'hellip)
(define ae   'aelig)
(define oq   'ldquo)
(define cq   'rdquo)
(define amp  'amp)
(define AE   'AElig)
